apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-temp.fullname" . }}
  labels:
    {{- include "django-temp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    {{- include "django-temp.selectorLabels" . | nindent 4 }}
