all:
  hosts:
    k8s_master:
      ansible_host: 84.252.143.154
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    k8s_worker:
      ansible_host: 51.250.106.129  
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

k8s_master:
  hosts:
    k8s_master:

k8s_workers:
  hosts:
    k8s_worker:
