apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diplom-ingress
  namespace: diplom
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # microk8s default
  rules:
  - host: diplom.local  # или *
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diplom-app
            port:
              number: 80

