apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diplom
spec:
  rules:
  - host: *  # или *
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diplom-app
            port:
              number: 80

