apiVersion: v1
kind: Service
metadata:
  name: diplom-app
  namespace: diplom
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080  # 30000-32767
  selector:
    app: diplom
