serviceAccount:
  create: false
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

image:
  repository: emdon2106/diplom-django  # твой Docker Hub / YCR
  tag: ""
  pullPolicy: Always

replicaCount: 2

service:
  type: NodePort
  port: 80
  targetPort: 3003

postgresql:
  enabled: true
  auth:
    postgresPassword: "password"  # меняй!
    username: "vinhle"
    password: "password"
    database: "tutorial-dev"
  primary:
    persistence:
      size: 5Gi
    service:
      port: 5432


django:
  dbHost: "{{ .Release.Name }}-postgresql"
  dbName: "tutorial-dev"
  dbUser: "vinhle"
  dbPass: "password"


ingress:
  enabled: false  # включи позже
